export default {
  MIN_LABYRINTH_SIZE: 2,
  MAX_LABYRINTH_SIZE: 15,

  DEFAULT_LABYRINTH_WIDTH: 5,
  DEFAULT_LABYRINTH_HEIGHT: 5,

  DIRECTION_TOP: 'top',
  DIRECTION_BOTTOM: 'bottom',
  DIRECTION_LEFT: 'left',
  DIRECTION_RIGHT: 'right',
};